-- AlterTable
ALTER TABLE "Cake" ADD COLUMN IF NOT EXISTS "isCustomQuote" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "CakePrice" ADD COLUMN IF NOT EXISTS "isCustomQuote" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CakePrice" ALTER COLUMN "price" DROP NOT NULL;
